### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by sjackman** [adarob/eXpress#13]
The URLs http://bio.math.berkeley.edu/eXpress and http://pachterlab.github.io/eXpress don't work. Is this the correct repository from which to download eXpress?

**Comment by adarob** [comment]
This should be fixed now.

**Comment by sjackman** [comment]
Thanks, Adam.

**Comment by sjackman** [comment]
> This GitHub site now serves as the project archive.

It looks like this text was intended to be a link, but isn't.

**Comment by tmozgach** [comment]
@sjackman  I used the following link in the formulae: https://pachterlab.github.io/eXpress/downloads/express-1.5.1/express-1.5.1-src.tgz
