### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by jonchang** [adarob/eXpress#21]
We package express for Homebrew and we'd rather not carry around a bunch of patches to get express to build on newer machines. It's OK if binaries aren't released, we just need a new tag to get things moving along once https://github.com/adarob/eXpress/pull/20 is merged.

c.f. https://github.com/brewsci/homebrew-bio/issues/832, https://github.com/brewsci/homebrew-bio/pull/833
and a similar request from Debian https://github.com/adarob/eXpress/issues/15

**Comment by adarob** [comment]
Done.

**Comment by jonchang** [comment]
Thanks! Much appreciated for the quick response.
